import styles from './HowItWorks.module.css';

const STEPS = [
  {
    number: '01',
    title: 'Enter your health data',
    description: 'Provide basic personal metrics, blood pressure readings, cholesterol and glucose levels, and lifestyle information across four guided steps.',
  },
  {
    number: '02',
    title: 'ML model analyzes signals',
    description: 'A trained cardiovascular disease prediction model evaluates the combined weight of your inputs to estimate relative risk.',
  },
  {
    number: '03',
    title: 'Receive your risk profile',
    description: 'Your personalized risk score is presented with context, input signal review, and a plain-language summary of contributing factors.',
  },
];

export default function HowItWorks() {
  return (
    <section id="how-it-works" className={styles.section} aria-labelledby="how-title">
      <div className={styles.inner}>
        <div className={styles.header}>
          <span className={styles.eyebrow}>METHODOLOGY</span>
          <h2 id="how-title" className={styles.title}>How the assessment works</h2>
          <p className={styles.desc}>
            A three-stage process from data input to intelligent risk estimation.
          </p>
        </div>

        <div className={styles.steps}>
          {STEPS.map((step, i) => (
            <div key={step.number} className={styles.step}>
              <div className={styles.stepMeta}>
                <span className={styles.stepNumber}>{step.number}</span>
                {i < STEPS.length - 1 && <span className={styles.stepLine} aria-hidden="true" />}
              </div>
              <div className={styles.stepContent}>
                <h3 className={styles.stepTitle}>{step.title}</h3>
                <p className={styles.stepDesc}>{step.description}</p>
              </div>
            </div>
          ))}
        </div>

        <div className={styles.note}>
          <div className={styles.noteIcon} aria-hidden="true">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
              <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
            </svg>
          </div>
          <p className={styles.noteText}>
            This tool is for informational purposes only and is not a substitute for professional medical advice.
            All assessments are generated by a statistical model and carry inherent uncertainty.
          </p>
        </div>
      </div>
    </section>
  );
}
